export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};

export const cartActionTypes = {
  ADD_PRODUCTS: "ADD_PRODUCTS",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
};
